services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    env_file:
      - ./.env
    ports:
        - 5672:5672
        - ${HABBITMQ_PORT}:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
    environment:
        - RABBITMQ_DEFAULT_USER=${HABBITMQ_USER}
        - RABBITMQ_DEFAULT_PASS=${HABBITMQ_PASS}

networks:
  rabbitmq_go_net:
    driver: bridge